-- begin BILLPRACTISE_BILL
create unique index IDX_BILLPRACTISE_BILL_UNIQ_NAME on BILLPRACTISE_BILL (NAME)^
create index IDX_BILLPRACTISE_BILL_NAME on BILLPRACTISE_BILL (NAME)^
-- end BILLPRACTISE_BILL

-- begin BILLPRACTISE_OPERATION
alter table BILLPRACTISE_OPERATION add constraint FK_BILLPRACTISE_OPERATION_ON_BILL foreign key (BILL_ID) references BILLPRACTISE_BILL(ID)^
create index IDX_BILLPRACTISE_OPERATION_ON_BILL on BILLPRACTISE_OPERATION (BILL_ID)^
-- end BILLPRACTISE_OPERATION
